<?php
	$request  = $this->getFront()->request;
	$response = $this->getFront()->response;
	
	$response->setHeader('Vary', 'Accept');
	
	if ($request->isAcceptedMime('application/xhtml+xml')) {
		$response->setHeader('Content-Type', 'application/xhtml+xml; charset=iso-8859-1', true);
		$doctype = $this->doctype('doctype', 'XHTML_TRANS');
	} else {
		$response->setHeader('Content-Type', 'text/html; charset=iso-8859-1', true);
		$doctype = $this->doctype('doctype', 'HTML4_TRANS');
	}
	
	echo $doctype ."\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
	<head>
		<title><?php echo TITLE .' - '. $this->title; ?></title>
		<link rel="stylesheet" href="/css/styles" />
	</head>
	<body>
		<div id="body">
			<div id="header">
				<div id="menu">
					<?php echo $this->renderPartial('backendmenu', 'default'); ?>
				</div>
			</div>
			<div id="wrapper">
				<?php
					echo $this->getPlaceholder('_sf_content');
				?>
				<br class="clear" />
			</div>
			<div id="footer">
				<ul>
					<li>
						Du är inloggad som: <?php echo $this->identity; ?>,
						<a href="<?php echo $this->host .'/stadium/logout'; ?>">Logga ut</a>
					</li>
					<li id="last">
						Copyright © 2007 Spiroo Digital Creations
					</li>
				</ul>
			</div>
		</div>
	</body>
</html>