<?php
/**
 * 
 * Generated by
 * Smash Framework Commentator
 * with PHP Version 5.3.4
 * 
 *  DESCRIPTION
 * Smash Framework is a Open Source PHP web framework to make it easier, efficient and more fun to create web applications.
 * 
 *  LICENSE
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author      Joel Denke <mail@happyness.se>
 * @category    Smash - Smash Makes A Sweet Harmony
 * @copyright   (C) 2011 Joel Denke
 * @license     http://www.opensource.org/licenses/gpl-3.0.html - GNU General Public License version 3
 * @version     alpha 0.1
 */
	namespace Smash\Mvc\Model\Driver;

	use   Smash\Core,
		Smash\Library,
		Smash\Error,
		Smash\Inflector,
		Smash\Mvc\Model\Driver,
		Smash\Mvc\Model as DB;

	/**
	 * Description goes here ...
	 * 
	 * @namespace    Smash\Mvc\Model\Driver
	 * @uses         Smash\Core,  Smash\Library,  Smash\Error,  Smash\Inflector,  Smash\Mvc\Model\Driver,  Smash\Mvc\Model as DB
	 * @extends      Smash\Mvc\Model\Driver
	 * @interfaces   Smash\Mvc\Model\Driver\Surface
	 * @package      Pdo
	 * @author       Joel Denke <mail@happyness.se>
	 * @license      http://www.opensource.org/licenses/gpl-3.0.html - GNU General Public License version 3
	 */
	class Pdo extends Driver implements Surface
	{
		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $options (Array)
		 */
		public function connect(array $options = array())
		{
			if (!extension_loaded('pdo')) {
				throw Core::error('Extension pdo is not loaded');
			}

			$hostname = $this->getDSN('hostname');
			/**
			 * Description goes here ...
			 * 
			 * @access   public
			 * @param    $model (Smash\Mvc\Model Object, required)
			 */
			$username = $this->getDSN('username');
			$password = $this->getDSN('password');
			$database = $this->getDSN('database');
			$database = empty($database) ? '' : ';dbname='. $database;

			$port     = $this->getDSN('port');
			$socket   = $this->getDSN('protocol') == 'unix' ? $this->getDSN('socket') : null;

			if ($this->getDSN('protocol') == 'unix') {
				$host = 'unix_socket='. $this->getDSN('socket');
			} else {
				$host = "host=$hostname;port=$port";
			}
/**
 * Description goes here ...
 * 
 * @access   public
 */

			try {
				$this->connection = new \PDO($this->getDSN('driver') .':'. $host . $database, $username, $password, $options);
				$this->connected  = true;
			} catch (\PDOException $e) {
				throw Core::error($e->getMessage(), $e->errorInfo, (int)$e->getCode());
			}
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function close()
		{
			/**
			 * Description goes here ...
			 * 
			 * @access   public
			 */
			$this->connected = false;
			$this->connection = null;
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $string (required)
		 */
		public function escape($string)
		{
			return $this->connection->quote($string);
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function getIdentifierSymbol()
		{
			return '`';
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function errInfo()
		{
			/**
			 * Description goes here ...
			 * 
			 * @access   public
			 */
			$error = $this->connection->errorInfo();
			return empty($error) ? 'No error occured' : $error;
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function errCode()
		{
			$errno = (int) $this->connection->errorCode();
			return $errno > 0 ? $errno : 'No error occured';
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function select()
		{
			/**
			 * Description goes here ...
			 * 
			 * @access   public
			 */
			if (PDO::getAttribute(PDO::ATTR_DRIVER_NAME) == 'mysql') {
				return Library::factory('mvc.model.driver.select.sql', $this);
			}
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $index (optional)
		 */
		public function update($table, array $data, $where = null)
		{
			$values = array();

			foreach ($data as $key => $val) {
				$values[] = "$key = ". $this->quote($val);
			}

			$sql = sprintf(
				/**
				 * Description goes here ...
				 * 
				 * @access   public
				 * @param    $dsn (required)
				 */
				'UPDATE %s SET %s %s',
				$this->quoteIdentify($table),
				implode(', ', $values),
				(!empty($where)) ? 'WHERE ' . $where : null
			);
/**
 * Description goes here ...
 * 
 * @access   public
 * @param    $index (required)
 * @param    $value (required)
 */

			return $this->prepare($sql);
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $table (required)
		 * @param    $whereClause (required)
		 */
		public function delete($table, $whereClause)
		{
			$sql = sprintf('DELETE FROM %s WHERE %s', $this->quoteIdentify($table), $whereClause);
			return $this->prepare($sql);
		}
/**
 * Description goes here ...
 * 
 * @access   public
 * @param    $index (required)
 */

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $table (required)
		 * @param    $data (Array, required)
		 */
		public function insert($table, array $data)
		{
			$values = array();

			foreach (array_values($data) as $value) {
				$values[] = $this->quote($value);
			}

			/**
			 * Description goes here ...
			 * 
			 * @access   public
			 * @param    $sql (required)
			 */
			$fields = implode(array_keys($data), ', ');
			$values = implode($values, ', ');
			$sql    = sprintf('INSERT INTO %s (%s) VALUES (%s)', $this->quoteIdentify($table), $fields, $values);

			return $this->prepare($sql);
		}
/**
 * Description goes here ...
 * 
 * @access   public
 */

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $sql (required)
		 */
		public function prepare($sql)
		{
			$this->connect();
			$stmt = $this->getStatement();
			/**
			 * Description goes here ...
			 * 
			 * @access   protected
			 * @param    $sql (required)
			 */
			return $stmt->prepare($sql);
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function getStatement()
		{
			return Library::factory('mvc.model.driver.statement.pdo', $this);
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $sql (required)
		 * @param    $connection (optional)
		 */
		public function query($sql, $connection = null)
		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $type (required)
		 */
		{
			$pdo = ($connection instanceof \PDO) ? $connection : $this->connection;

			if ($this->getOption('buffering') && $pdo->getAttribute(PDO::ATTR_DRIVER_NAME) == 'mysql') {
				PDO::setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true);
			}

			$stmt = $pdo->query($sql);

			if (!$stmt) {
				throw Core::error($this->errInfo(), array('query' => $sql), $this->errCode());
			} else {
				$this->setLastQuery($sql);

				if ($stmt instanceof \PDOStatement) {
					return Library::factory('mvc.model.result', $this, $stmt->execute());
				} else {
					return $stmt;
				}
			}
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 * @param    $result (required)
		 * @param    $mode (optional)
		 */
		public function fetch($result, $mode = null)
		{
			if (!$result instanceof  \PDOStatement) {
				throw Core::error('Invalid result resource: %result', array('result' => $result));
			} else {
				if (is_int($mode)) {
					return is_int($mode) ? $result->fetch($mode) : $result->fetch();
				/**
				 * Description goes here ...
				 * 
				 * @access   public
				 * @param    $value (required)
				 */
				}
			}
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function begin()
		{
			/**
			 * Description goes here ...
			 * 
			 * @access   public
			 * @param    $value (required)
			 */
			$this->connection->beginTransaction();
			$hasTransaction = true;
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function commit()
		{
			$this->connection->commit();
			$hasTransaction = false;
		}

		/**
		 * Description goes here ...
		 * 
		 * @access   public
		 */
		public function rollback()
		{
			$this->connection->rollback();
			$hasTransaction = false;
		}
	}
?>